### ISSUE TITLE
Hang on `wait` depending on `@inbounds`

### ISSUE THREAD

**Issue by luraess** [JuliaGPU/AMDGPU.jl#332]
AMDGPU (`#master` and `#jps/dev`) hangs on wait when explicitly handling kernel signals with different queue priorities. In the below MWE, removing `@inbounds` statements in the kernel leads to the code to hang on `wait(kern_sig[2])`. @jpsamaroo @vchuravy any idea why?

Note:
- waiting on the `ROCSignal()` or `ROCKernelSignal` has no effect and seems to deliver same accurate results. 
- low `nx` seem not to show this behaviour
- tests where performed on MI250x GPU

```julia
using AMDGPU

function my_kernel2!(A,B,c)
    ix = (workgroupIdx().x - 1) * workgroupDim().x + workitemIdx().x
    @inbounds A[ix] = A[ix] + B[ix] + c
    return
end

function mwe()
    println("device $(AMDGPU.default_device_id())")
    nx      = 1024*1024
    grid    = (nx,1,1)
    threads = (512,1,1)
    # init
    A = ROCArray(zeros(Float64,nx))
    B = ROCArray( ones(Float64,nx))
    c = rand()
    # queues & signals
    rocqueues = Vector{AMDGPU.ROCQueue}(undef,2)
    for is = 1:2
        rocqueues[is] = is == 1 ? ROCQueue(AMDGPU.default_device(); priority=:high) : ROCQueue(AMDGPU.default_device())
    end
    sig2 = [ROCSignal(), ROCSignal()]
    kern_sig = Vector{AMDGPU.ROCKernelSignal}(undef,2)
    # some action
    for it = 1:2
        println("-> it $it")
        for is=1:2
            AMDGPU.HSA.signal_store_screlease(sig2[is].signal[],1)
        end
        println("start loop")
        for is = 1:2
            kern_sig[is] = @roc wait=false mark=false signal=sig2[is] queue=rocqueues[is] groupsize=threads gridsize=grid my_kernel2!(A,B,c)
            println("hi $is")
        end
        println("hi 3")
        wait(kern_sig[1])
        # wait(sig2[1])
        println("mpi exchange")
        wait(kern_sig[2])
        # wait(sig2[2])
        println("bye loop")
    end
    println("done.")
    return
end

mwe()

```

**Comment by jpsamaroo** [comment]
The bug here is comprised of multiple parts:
- We have a regression on `master` where async queue errors are not propagated through `wait` (so any kernel which triggers a queue error appears to hang the CPU, even though the GPU is actually inactive)
- Parallel queues appear to cause issues in ROCR's ability to consistently allocate scratch memory (which is likely a ROCR bug?)
- Bounds checking (and probably error paths in general) cause large static scratch allocations of `2^14` per-lane, which is excessive for most kernels

The solution I've pushed to `jps/dev` adds an environment variable (`JULIA_AMDGPU_MAX_SCRATCH`) and runtime knob (`AMDGPU.Runtime.set_max_scratch!`) which set a global limit for per-lane scratch; i.e. when a kernel attempts to statically request more than this amount of scratch, we instead cap it to this global limit. Assuming the kernel never actually uses the amount of scratch it had requested, everything should continue working correctly.

**Comment by luraess** [comment]
Would be interesting to follow up investigations on the ROCR side (or ping someone with the knowledge to do so). Thanks for the insights @jpsamaroo

**Comment by utkinis** [comment]
This issue persists on `pxl-th/hiprtc` branch as well when calling `AMDGPU.HIP.wait` on `AMDGPU.HIP.HIPEvent`, but instead of hanging, the code crashes with the following error:

```
:0:rocdevice.cpp            :2648: 2415296931522 us: 57935: [tid:0x14aaa82af700] Device::callbackQueue aborting with error : HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events. code: 0x1008

[57935] signal (6.-6): Aborted
in expression starting at /pfs/lustrep4/scratch/project_465000139/ivutkin/temp/hiptest.jl:44
Allocations: 22036260 (Pool: 22016159; Big: 20101); GC: 28
Aborted
```

**Comment by luraess** [comment]
For cross-ref #423

**Comment by pxl-th** [comment]
Same as https://github.com/JuliaGPU/AMDGPU.jl/issues/388#issuecomment-1625458560.
